#!/bin/env bash
# still need this so it picks up wireless interfaces could probably just use /etc/conky
for i in `ls /sys/class/net/`;do 
  echo -n "[ ${i}: \${upspeed ${i}} - \${downspeed ${i}} ] " >> /home/spareproject/.conkyrc
  echo -n "[ ${i}: \${upspeed ${i}} - \${downspeed ${i}} ] " >> /home/admin/.conkyrc
done
echo -n "[ bridge: \${upspeed bridge} - \${downspeed bridge} ] [ internal: \${upspeed internal} - \${downspeed internal} ] [ tor: \${upspeed tor} - \${downspeed tor} ] [ CPU: \${cpu cpu0}% ] [ RAM: \${memperc}% ] [ LOAD: \${loadavg 1},\${loadavg 2},\${loadavg 3} ] [ \${uptime} | \${time %a %b %d %I:%M%P} ] [ Battery: \${battery_percent BAT0}% ]" >> /home/spareproject/.conkyrc
echo -n "[ bridge: \${upspeed bridge} - \${downspeed bridge} ] [ internal: \${upspeed internal} - \${downspeed internal} ] [ tor: \${upspeed tor} - \${downspeed tor} ] [ CPU: \${cpu cpu0}% ] [ RAM: \${memperc}% ] [ LOAD: \${loadavg 1},\${loadavg 2},\${loadavg 3} ] [ \${uptime} | \${time %a %b %d %I:%M%P} ] [ Battery: \${battery_percent BAT0}% ]" >> /home/admin/.conkyrc


