#!/bin/env bash
for i in `ls /sys/class/net/`; do if [[ ${i} != lo ]]; then macchanger -rb ${i}; fi; done
hexchars="0123456789abcdef"
for i in notbridge.netdev internal.netdev tor.netdev;do
testing="24:df:86$( for i in {1..6};do echo -n ${hexchars:$(( $RANDOM % 16 )):1}; done | sed -e 's/\(..\)/:\1/g')"
sed -i "s/mac/${testing}/" /etc/systemd/network/${i}
done
